version: "3"

services:
  frontend:
    container_name: frontend-container
    build: ./frontend
    image: 030395/waecm-2020-group-20-bsp-2-frontend:v1
    volumes:
      - app:/usr/src/app/frontend
    ports:
      - 4200:4200
    links: 
      - backend
    depends_on:
      - backend

  backend:
    container_name: backend-container
    restart: always
    build: ./backend
    image: 030395/waecm-2020-group-20-bsp-2-backend:v1
    environment:
      REDDIT_USERNAME: 'CoolerBamio'
      REDDIT_PASSWORD: 'JFeqw7pAHK3fZAcP7c83qy6Sx'
      REDDIT_CLIENT_ID: 'E3-s2ZGChD9J2A'
      REDDIT_CLIENT_SECRET: 'rO7VOkBeeMWl7Row4-hF2DZe2dM'
      WAECM_GROUP_NAME: 'waecm-2020-group-20'
    volumes:
      - app:/usr/src/app/backend
    ports:
      - 3000:3000
    depends_on:
      - dbs

  dbs:
    container_name: dbs_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: app-dbs
    volumes:
      - app:/var/lib/postgresql/data
    ports:

      - 5432:5432


volumes:
  app:
