version: "3"

services:
  backend:
    container_name: backend-container
    restart: always
    build: backend
    ports:
      - "3000:3000"

  frontend:
    container_name: frontend-container
    build: frontend
    ports:
      - "4200:4200"
