version: "3"

services:
  frontend:
    container_name: frontend-container
    image: 030395/waecm-2020-group-20-bsp-1-frontend:v2
    volumes:
      - app:/usr/src/app/frontend
    ports:
      - ${FRONTEND_PORT}:4200
    depends_on:
      - backend

  backend:
    container_name: backend-container
    restart: always
    image: 030395/waecm-2020-group-20-bsp-1-backend:v1
    volumes:
      - app:/usr/src/app/backend
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      - dbs

  dbs:
    container_name: dbs_container
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: app-dbs
    volumes:
      - app:/var/lib/postgresql/data
    ports:
      - ${DBS_PORT}:5432

volumes:
  app:
