name: BUILD FRONTEND

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ls
    - run: npm install
    - run: npm run build
    - run: mkdir zip
    - run: sudo apt install zip
    - run: zip -r ./zip/build.zip ./dist/frontend
    - run: ls
    - name: upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./zip/build.zip
    - name: download build artifact
        uses: actions/download-artifact@v1
        with:
          name: build
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "build"
        remoteDir: "waecm"